# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.



development:
  secret_key_base: 08397c57bb42360f1a738e2fa2502b3f15cac72914cfcb23029017948c1af5199537a382f69606a6af93cce8a8a7fb64b916446ff47be92bf27550098b46d707

test:
  secret_key_base: be5283d9becae80d2356087191cf59935b9316d7e7275172b77c7537aac41c409fa006333687c4ec399957e5c7f3a36f2109a8878e1f8c5f00147133cf139875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>